### ISSUE TITLE
modules which are used in this code are not listen as prerequisite

### ISSUE THREAD

**Issue by makeitcloudy** [citrixguyblog/PowerShellRDSDeployment#1]
looks like that there is a requirement that on the host when you are running this code, you have to have all the modules which you are importing within the code, or have it rewritten this way that it is importing them via implicit remoting to have them available in case you are going to run it from one place which is an authoring node for instance.
* code needs to be rewritten or 
* you have to make sure that all the modules are already in place or
* you may have run piece of current code from different nodes.

**Comment by citrixguyblog** [comment]
Hello tansei,
the modules are getting installed if they are missing on the "Hydration" machine.

#region "Check Prerequisites"
Write-Verbose "Check Prerequisites" -Verbose

if (Get-WindowsFeature -Name RSAT-AD-Tools, RSAT-DNS-Server){
   Write-Verbose "Needed PowerShell Modules available." -Verbose
} else {    
    Write-Verbose "Needed PowerShell Modules will be installed." -Verbose
    Install-WindowsFeature RSAT-AD-Tools, RSAT-DNS-Server
    Write-Verbose "Needed PowerShell Modules have been installed." -Verbose
} #end if Get-WindowsFeature
